---
- name: Install Monit
  apt:
    name: monit

- name: Update Monit configuration
  template:
    src: monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0700
  notify: Restart Monit
