---
- name: Warn users if the server's Linux distribution is not Ubuntu 14.04
  pause:
    prompt: "Ubuntu 14.04 is the only officially supported distribution; the setup will probably fail. Press Enter if you still want to continue."
  when: ansible_distribution != "Ubuntu" or ansible_distribution_major_version != "14"

# Set default variables
- include: set-default-variables.yml

- name: Ensure the APT cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Streisand common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ adios_common_packages }}"
