---
- name: Create network
  local_action:
    module: gce_net
    name: "{{ gce_network }}"
    state: "present"
    ipv4_range: "{{ gce_ipv4_range }}"
    credentials_file: "{{ gce_json_file_location }}"
    project_id: "{{ gce_project_id }}"
    service_account_email: "{{ gce_service_account_email }}"

- name: Open the SSH port in the GCE firewall
  local_action:
    module: gce_net
    name: "{{ gce_network }}"
    fwname: "adios-ssh"
    allowed: "tcp:{{ ssh_port }}"
    state: "present"
    src_range: 0.0.0.0/0
    service_account_email: "{{ gce_service_account_email }}"
    credentials_file: "{{ gce_json_file_location }}"
    project_id: "{{ gce_project_id }}"
  when: open_ssh_port_only
