---
- name: Get the default SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: ssh_key

- name: Get the latest Ubuntu 14.04 image ID from the Linode API
  shell: curl -s 'https://api.linode.com/?api_key={{ linode_api_key }}&api_action=avail.distributions' | {{ ansible_python_interpreter }} -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j["DATA"] if img["LABEL"]=="Ubuntu 14.04 LTS"][0]["DISTRIBUTIONID"]'
  args:
    warn: no
  register: linode_ubuntu_distribution_id

- name: Create the server
  linode:
    api_key: "{{ linode_api_key }}"
    name: "{{ linode_server_name }}"
    plan: "{{ linode_plan_id }}"
    datacenter: "{{ regions[linode_datacenter] }}"
    distribution: "{{ linode_ubuntu_distribution_id.stdout }}"
    ssh_pub_key: "{{ ssh_key.stdout }}"
    wait: yes
  register: adios_server

- name: Wait until the server has finished booting and OpenSSH is accepting connections
  wait_for:
    host: "{{ adios_server.instance.ipv4 }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600

- name: Create the in-memory inventory group
  add_host:
    name: "{{ adios_server.instance.ipv4 }}"
    groups: adios-host

- name: Set the adios_ipv4_address variable
  set_fact:
    adios_ipv4_address: "{{ adios_server.instance.ipv4 }}"

- name: Set the adios_server_name variable
  set_fact:
    adios_server_name: "{{ linode_server_name }}"
