---
- name: Provision the Rackspace Server
  hosts: localhost
  gather_facts: no
  vars:
    regions:
      "1": "ORD"
      "2": "DFW"
      "3": "HKG"
      "4": "IAD"
      "5": "SYD"
  vars_prompt:
    - name: "rackspace_region"
      prompt: >
        What region should the server be located in?
          1. Chicago
          2. Dallas
          3. Hong Kong
          4. Northern Virginia
          5. Sydney
        Please choose the number of your region. Press enter for default (#3) region.
      default: "3"
      private: no

    - name: "rackspace_server_name"
      prompt: "\nWhat should the server be named? Press enter for default (adios).\n"
      private: no
      default: "adios"

    - name: "rackspace_username"
      prompt: "\nWhat is your Rackspace username?\n"
      private: no

    - name: "rackspace_api_key"
      prompt: "\n\nThe following information can be found in the Rackspace Cloud Control Panel.\nhttps://mycloud.rackspace.com/\n\nWhat is your Rackspace API key?\n"
      private: no

  roles:
    - genesis-rackspace

- include: adios.yml
